{"title":"Next.JS dynamic import and 500 error","link":"https://www.llun.me/posts/dev/2024-03-08-nextjs-dynamic-import-and-500-error","date":1709921368000,"content":"<p>Another problem come by, we have a mysterious 500 error showing after we deploy a new page that move to Next.JS. The page works fine and returns however, when users go to the next page, it shows 500 error. Open that page directly doesn’t make it returns 500</p>\n<p>Looking into the logs, it’s showing like this</p>\n<pre><code> ⨯ Error: Cannot find module 'test'\n    at /path/to/project/.next/server/pages/[[...page]].js:1:182 {\n  code: 'MODULE_NOT_FOUND'\n</code></pre>\n<p>Which point to the dynamic loading that is using in the first page and it’s not supposed to affect the other page. The problem here is the path that import is not exists and normally this would get catch in the build time but this is not happened because this part of the code is using variable to point to the module name.</p>\n<p>Changing the file name to <code>page.js</code> fix the problem, however, this makes the page not catching all the requests. Another way is fixing the variable value and making sure the import path must exists but both of these doesn’t answer why does the error from first page showing in the subsequent page when click on the link.</p>\n<p>Looking into Next.JS server code, when the page is render, it’s try to load all the dynamic imports here <a href=\"https://github.com/vercel/next.js/blob/v14.1.3/packages/next/src/server/render.tsx#L630\" target=\"_blank\">https://github.com/vercel/next.js/blob/v14.1.3/packages/next/src/server/render.tsx#L630</a> which will call through <code>ALL_INITIALIZERS</code> here <a href=\"https://github.com/vercel/next.js/blob/v14.1.3/packages/next/src/shared/lib/loadable.shared-runtime.tsx#L275-L279\" target=\"_blank\">https://github.com/vercel/next.js/blob/v14.1.3/packages/next/src/shared/lib/loadable.shared-runtime.tsx#L275-L279</a>. This was shared between catch all page and the page that more specific.</p>\n<p>Here is a sample project testing this issue <a href=\"https://github.com/llun/nextjs-catchall-dynamic-import-500\" target=\"_blank\">https://github.com/llun/nextjs-catchall-dynamic-import-500</a></p>\n<p>The solution for this is, making sure that the dynamic imports are exists or don’t use catch all like this. It can make the NextJS returns 500 error to a random requests.</p>\n","author":"Maythee Anegboonlap","siteTitle":"@llun story","siteHash":"e492a4c5a091b6624e5872d8d003bc73eb1166cc8f88db58c44e1f8dfb9c7252","entryHash":"471ff8a84e1566fbfd34b177e94bcf07c26ebf259ffdea93b1bb2782de68ff41","category":"Category1"}